### PR TITLE
Fix use after free in Main.cpp (issue #846)

### LINKED ISSUE #846: Use after free in Main.cpp
On latest clang trunk, the code
```
const char *text = ("Content of this directory moved to " +
							                    xdg_data_home + "/openspades")
							                     .c_str();
```
in https://github.com/yvt/openspades/blob/master/Sources/Gui/Main.cpp#L428

causes the warning 
```
warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling]
```
because `xdg_data_home  + ...` creates a temporary `std::string` which is destroyed at the end of the line, and `text` then points into that destroyed string.

### PR DESCRIPTION
**Pull request by dtomlinson-ga**
Create c-string to store filepath before concatenating with output message. [Fix #846](https://github.com/yvt/openspades/issues/846)

### CODE REVIEW

**Comment by dtomlinson-ga** [comment]
I don't know if this is the best way to go about doing this, but I wanted to dip my toes into contributing to this project. Let me know if anything needs to change :)

File: Sources/Gui/Main.cpp [hunk 1]
```diff
@@ -425,9 +425,8 @@ int main(int argc, char **argv) {
 						SDL_RWops *io = SDL_RWFromFile(
 						  (home + "/.openspades/CONTENT_MOVED_TO_NEW_DIR").c_str(), "wb");
 						if (io != NULL) {
-							const char *text = ("Content of this directory moved to " +
-							                    xdg_data_home + "/openspades")
-							                     .c_str();
+							const char *directory = (xdg_data_home + "/openspades").c_str();
+							const char *text = ("Content of this directory moved to " + directory).c_str();
```
[the remark this answers is not in the document]
Comment (dtomlinson-ga) [reply Sources/Gui/Main.cpp]: Thank you for the helpful feedback! I wasn't familiar with this usage of the `const char*` declaration, but looking around the code, declaring as a `std::string` as you described is definitely more prevalent.

File: Sources/Gui/Main.cpp [hunk 2]
```diff
@@ -425,10 +425,8 @@ int main(int argc, char **argv) {
 						SDL_RWops *io = SDL_RWFromFile(
 						  (home + "/.openspades/CONTENT_MOVED_TO_NEW_DIR").c_str(), "wb");
 						if (io != NULL) {
-							const char *text = ("Content of this directory moved to " +
-							                    xdg_data_home + "/openspades")
-							                     .c_str();
-							io->write(io, text, strlen(text), 1);
+							std::string text = ("Content of this directory moved to " + directory);
```
Comment (yvt) [inline Sources/Gui/Main.cpp]: Build is failing because `directory` is not defined.

Comment (dtomlinson-ga) [reply Sources/Gui/Main.cpp]: ... I need to stop writing these at 1 am. Sorry for the rookie mistake, should be fixed now!
